### ISSUE TITLE
${workspaceFolder} is ignored in path to clang-tidy

### ISSUE THREAD

**Issue by Wastus** [TimZoet/ClangTidyGUI#10]
We usually ship the tools we use with our workspace to make it easier to setup.

For this, I usually point to the tools via `${workspaceFolder}/xyz/bla.exe` I tried this with your extension and sadly it didn't replace the `${workspaceFolder}` with the actual folder.

**Comment by TimZoet** [comment]
This issue was addressed in the latest version.

**Comment by Wastus** [comment]
Perfect, works fine.
