### ISSUE TITLE
Use c_cpp_properties.json to find the compile_commands.json

### ISSUE THREAD

**Issue by Wastus** [TimZoet/ClangTidyGUI#11]
We have setup the workspace to use C/C++ extension from Microsoft (ms-vscode.cpptools) which provides a `c_cpp_properties.json`.

In our case we have multiple configurations to select from and each has their own `compile_commands.json`. Depending on which configuration we switch to, a different one is used.

It would be very neat to get the currently active `compile_commands.json` for clang-tidy based on the active configuration.
I don't think that `cpptools` provides an interface for this directly.

While researching this I found `${command:cpptools.activeConfigName}` which would be usable as a first step because our configuration names and the folders where the `compile_commands.json` live are related to each other.

**Comment by TimZoet** [comment]
The configuration name of the cpptools extension wasn't well documented, but with some effort I managed to implement it. You can now use a new variable ${cpptools.config}, which is substituted with the name of the selected configuration. It should be possible to e.g. use `${workspaceFolder}/build/${cpptools.config}`as build path. Variable is also supported by some of the other path settings. See the latest version.

I don't have a full VSC C++ development environment on Windows and only tested it with a dummy project, so I'd appreciate it if you could do some slightly more extensive testing and report back here.

**Comment by Wastus** [comment]
I've tried it with my current setup and it works fine. Switching between configurations works great and now automatically uses the correct `compile_commands.json`.

Thank you for the very fast implementation. Keep up the good work.
