### ISSUE TITLE
Diagnostics panel remains empty

### ISSUE THREAD

**Issue by stephanfr** [TimZoet/ClangTidyGUI#12]
I am using ClangTidyGUI on a project running on an RPi4.  The clang-tidy tool runs and a result file appears in '/build/clang-tidy' but nothing is rendered in the diagnostics panel.  I can toggle the various checks in the 'checks' panel and those are persisted.

Any suggestions on what I might be doing wrong ?

**Comment by Wastus** [comment]
Have you clicked the small refresh button in the diagnostic view?

It only appears on mouse over:
![image](https://user-images.githubusercontent.com/16320076/109634772-eb926100-7b49-11eb-905e-8086bedc198c.png)

**Comment by TimZoet** [comment]
@stephanfr, are you still encountering this issue?

**Comment by stephanfr** [comment]
Sorry for the slow response, busy at work then vacation.

I apologize for leaving out one very important piece of information - I am running a remote session using SSH to an RPi.  I have not problem picking up the yaml files from the remote filesystem, but those are not being mapped into the GUI extension.

**Comment by TimZoet** [comment]
Yeah, I'm afraid that is kind of outside the scope of this extension. All I could offer is a potential workaround:

It is possible to set an arbitrary output directory in which the extension will look for the yaml files. If you use some other tool to sync that local folder with what's on your remote, it should work.
