### ISSUE TITLE
various exceptions

### ISSUE THREAD

**Issue by mumin16** [TimZoet/ClangTidyGUI#13]
[2021-04-05T09:17:35.625Z] Running clang-tidy on c:\Users\x64\CLionProjects\demo\main.cpp
[2021-04-05T09:17:41.272Z] An error occurred when running clang-tidy on c:\Users\x64\CLionProjects\demo\main.cpp:
Error: Command failed: clang-tidy --checks=* -p c:\Users\x64\CLionProjects\demo\build -export-fixes=c:\Users\x64\CLionProjects\demo\build\clang_tidy\44c13c596d4dcca300f6e721be4f240c.yaml c:\Users\x64\CLionProjects\demo\main.cpp
Assertion failed: Last.Offset <= Offset && "state transitions added out of order", file C:\src\llvm_package_1200-rc4\llvm-project\clang\lib\Basic\Diagnostic.cpp, line 194
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.	Program arguments: clang-tidy --checks=* -p c:\\Users\\x64\\CLionProjects\\demo\\build -export-fixes=c:\\Users\\x64\\CLionProjects\\demo\\build\\clang_tidy\\44c13c596d4dcca300f6e721be4f240c.yaml c:\\Users\\x64\\CLionProjects\\demo\\main.cpp
1.	<eof> parser at end of file
 #0 0x00007ff7496b96e6 C:\Program Files\LLVM\bin\clang-tidy.exe 0x13196e6 (C:\Program Files\LLVM\bin\clang-tidy.exe+0x13196e6)
 #1 0x00007ff7496b96e6 
 #2 0x00007ff7496b96e6 (C:\Program Files\LLVM\bin\clang-tidy.exe+0x13196e6)
 #3 0x00007ffe83ee1881 (C:\Windows\System32\ucrtbase.dll+0x71881)
 #4 0x00007ffe83ee2851 (C:\Windows\System32\ucrtbase.dll+0x72851)
 #5 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1728d49 C:\Program Files\LLVM\bin\clang-tidy.exe 0x17299a9
 #6 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1729ac2 C:\Program Files\LLVM\bin\clang-tidy.exe 0xe376bb
 #7 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0xe30e1f C:\Program Files\LLVM\bin\clang-tidy.exe 0xe30e1f
 #8 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0xe31ad2 C:\Program Files\LLVM\bin\clang-tidy.exe 0xdd94ae
 #9 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0xdd2178 C:\Program Files\LLVM\bin\clang-tidy.exe 0xe3fc41
#10 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0xdd278f C:\Program Files\LLVM\bin\clang-tidy.exe 0xe31b14
#11 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0xdd94ae C:\Program Files\LLVM\bin\clang-tidy.exe 0xdd2178
#12 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0xe3fc41 C:\Program Files\LLVM\bin\clang-tidy.exe 0xdd278f
#13 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x353105 C:\Program Files\LLVM\bin\clang-tidy.exe 0x3540ca
#14 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x355b9c C:\Program Files\LLVM\bin\clang-tidy.exe 0x16fefd3
#15 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x171955b C:\Program Files\LLVM\bin\clang-tidy.exe 0x16fe57e
#16 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x16ff4bc C:\Program Files\LLVM\bin\clang-tidy.exe 0x170521b
#17 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1702cad C:\Program Files\LLVM\bin\clang-tidy.exe 0x16ff4c7
#18 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x170521b C:\Program Files\LLVM\bin\clang-tidy.exe 0x16ff5c5
#19 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x16ff4c7 C:\Program Files\LLVM\bin\clang-tidy.exe 0x170521b
#20 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x17002d1 C:\Program Files\LLVM\bin\clang-tidy.exe 0x16ff4c7
#21 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x16dc31c C:\Program Files\LLVM\bin\clang-tidy.exe 0x1cf1bec
#22 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1eab2c3 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1cf73c5
#23 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1cd83c3 C:\Program Files\LLVM\bin\clang-tidy.exe 0x17808d0
#24 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x17a3d19 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1780781
#25 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x177fa43 C:\Program Files\LLVM\bin\clang-tidy.exe 0x1781f6a
#26 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x17a00ea C:\Program Files\LLVM\bin\clang-tidy.exe 0x3467
#27 0x00007ffe83ee41b5 C:\Program Files\LLVM\bin\clang-tidy.exe 0x235c3f0 (C:\Windows\System32\ucrtbase.dll+0x741b5)
#28 0x00007ffe83ee41b5 
#29 0x00007ffe83ee41b5 (C:\Windows\System32\ucrtbase.dll+0x741b5)
0x00007FF7496B96E6 (0x00001EB6E2F8FCC8 0x0000000000000000 0x0000000000000016 0x00007FF7496B96E0)
0x00007FFE83EE1881 (0x0000000000000001 0x00007FF700000000 0x0000000000000000 0x000000F3FE18ADF0), raise() + 0x1E1 bytes(s)
0x00007FFE83EE2851 (0x00007FFE00000003 0x00007FFE00000003 0x00007FF74B6AF5C6 0x00007FF74B6AF44C), abort() + 0x31 bytes(s)
0x00007FFE83EE41B5 (0x00000000000000C2 0x00007FF74B6AF5C6 0x000002893D62F8A8 0x0000000000000000), _get_wpgmptr() + 0x18A5 bytes(s)
0x00007FFE83EE44F1 (0x00007FF74A701652 0x000002893F8E7638 0x000002894217D8F0 0x00007FFE83E7FDE6), _wassert() + 0x71 bytes(s)
0x00007FF749AC8D49 (0x000000F3FE18AF90 0x00007FF749B0630D 0x000002893FBFB173 0x00000000804D54FC)
0x00007FF749AC99A9 (0x0000000000000000 0x0000000000000020 0x0000000000000000 0x0000000000000000)
0x00007FF749AC9AC2 (0x000000F3FE18B578 0x00007FF7496440EC 0x0000000000000000 0x000002893D702340)
0x00007FF7491D76BB (0x00000501804D54FC 0x00007FF749672217 0x0000000000000036 0x00000000004CFF7E)
0x00007FF7491D0E1F (0x000002893FBFABB8 0x000000000000000F 0x000000F3FE18B6B0 0x000000000000FB69)
0x00007FF7491D0E1F (0x0000000000000009 0x000000000000000F 0x00007FF7FFFFFFFF 0x0000005954504D45)
0x00007FF7491D1AD2 (0x000000F3FE18BA88 0x00007FF7496440EC 0x0000B44704DC86A9 0x000002893FBF003C)
0x00007FF7491794AE (0x00000000804D54B0 0x804D549100000001 0x000002893D618680 0x00000004804D5527)
0x00007FF749172178 (0x000002893D667D90 0x00007FF749172AB8 0x000000F3FE18BD18 0x00007FF749172AB8)
0x00007FF7491DFC41 (0x0000028900000002 0x0000B44704DC8579 0x0000000000000000 0x000000F3FE18C690)
0x00007FF74917278F (0x0000000000000009 0x000000000000000F 0x00000289FFFFFFFF 0x0000005954504D45)
0x00007FF7491D1B14 (0x0000D00472860101 0x0000000000000000 0x0000000000000000 0x00007FF7483AF319)
0x00007FF7491794AE (0x0000000000000220 0x00007FF700000000 0x000000F3FE18C0B8 0x0000000000000000)
0x00007FF749172178 (0x0000000000000000 0x0000000000000048 0x0000000000000000 0x0000000000000000)
0x00007FF7491DFC41 (0x0000B44704DCFE89 0x000000F3FE18C6C8 0x000002893F495528 0x0000000000000000)
0x00007FF74917278F (0x00000000000001E8 0x0000028941299E76 0x000000000000EE1F 0x000002893D667D90)
0x00007FF7486F3105 (0x000000F3FE18C8C8 0x000000F3FE18C8B0 0x000000F3FE18F328 0x0000028941290000)
0x00007FF7486F40CA (0x0000028940EC13E0 0x0000000000000000 0x0000000000000070 0x000002893D700CC0)
0x00007FF7486F5B9C (0x0000028941846050 0x00000289418469F0 0x0000028941846050 0x00007FF7483F091C)
0x00007FF749A9EFD3 (0x000000F3FE18CEB0 0x00000000FE18D500 0x0000000000000013 0x0000028940D37BF0)
0x00007FF749AB955B (0x00000289415EB8E0 0x00007FFE00000000 0x000002894217C6E0 0x000002894217B010)
0x00007FF749A9E57E (0x000000F3FE18D010 0x0000028900000000 0x00000289409D9C60 0x000002893D862A60)
0x00007FF749A9F4BC (0x0000B44704DCF3E9 0x0000000000000001 0x0000000000000000 0x0000028940D341C0)
0x00007FF749AA521B (0x000002893F05DD08 0x000000F300000000 0x000000F3FE18CFD0 0x000000F3FE18D1F0)
0x00007FF749AA2CAD (0x000000F3FE18D200 0x0000B44704DCEEB9 0x000000F3FE18D538 0x000000F3FE18D538)
0x00007FF749A9F4C7 (0x0000000000004340 0x0000B44704DCEE39 0x0000000000000000 0x0000028940464270)
0x00007FF749AA521B (0x0000028940EC0E60 0x0000000000000000 0x000000F3FE18D288 0x0000028941163010)
0x00007FF749A9F5C5 (0x000000F3FE18D3F0 0x0000028941163010 0x000002893F084686 0x000002893D862A60)
0x00007FF749A9F4C7 (0x0000000000000000 0x0000B44700000000 0x000000F3FE18D538 0x00007FFE83E7F05B)
0x00007FF749AA521B (0x0000000000000008 0x0000000000000000 0x000002893D5E0000 0x000000F3FE18D429)
0x00007FF749AA02D1 (0xFFFFFFFFFFFFFFF8 0x000002893D837AD0 0x000002893F087300 0x000002893D837AD0)
0x00007FF749A9F4C7 (0x0000000000394F59 0xFFFFFFFFFFFFF000 0x0000000000000000 0xFFFFFFFFFFFFF000)
0x00007FF749A7C31C (0x000000F3FE18D720 0x0000000000000000 0x000002893F088470 0x000000F3FE18D800)
0x00007FF74A091BEC (0x0000000000000000 0x00007FF74A0759DF 0x000002893D62F850 0x000000F301001213)
0x00007FF74A24B2C3 (0x000000010000000F 0x0000B44704DCEDB9 0x0000000000000000 0x0000000000000000)
0x00007FF74A0973C5 (0x000000F3FE18DB10 0x0000000000000000 0x000002893D667D90 0x00007FF749ABDED4)
0x00007FF74A0783C3 (0x000002893D666F50 0x000002893D667310 0x000002893D667610 0x0000000000000027)
0x00007FF749B208D0 (0x0000000000000012 0x00007FF74B75139D 0x0000000000000009 0x00007FF74B7513A7)
0x00007FF749B43D19 (0x000002893D669640 0x000002893D60D660 0x000002893D62E800 0x00007FFE83E7FDE6)
0x00007FF749B20781 (0x000002893D5E0000 0x0000028900000000 0x0000000000000000 0x0000000000000001)
0x00007FF749B1FA43 (0x0000000000000061 0x0000000000000000 0x000000023D700000 0x0000000000000000)
0x00007FF749B21F6A (0x000000F3FE18E8DC 0x0000000000000002 0x0000000000000000 0x0000028900000080)
0x00007FF749B400EA (0x000000F3FE18F071 0x00007FFE00000000 0x0000000000000000 0x0000000000000000)
0x00007FF7483A3467 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF74A6FC3F0 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFE85367034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFE86242651 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

**Comment by TimZoet** [comment]
This seems to be an issue with clang-tidy itself. Not much I can do here. You should probably open a bug report at https://bugs.llvm.org/.
