### ISSUE TITLE
fileFilter tests only file name without folder path

### ISSUE THREAD

**Issue by Semitalis** [TimZoet/ClangTidyGUI#9]
The current implementation does not allow to filter for files within certain subdirectories, e.g. following project folder hierarchy exists:
- extern
-- ignore.cpp
- impl
-- foo.cpp
- test
-- bar.cpp

I would expect to be able to use the following settings:
```
"clangtidy.sourcePath": "${workspaceFolder}",
"clangtidy.fileFilter": "(impl|test)/.*\\.(h|hpp|cpp)$",
```
Thus clang-tidy would be executed on files within impl and test folder, but not for the extern directory.

Alternatively, multiple paths for sourcePath would be allowed, e.g:
`"clangtidy.sourcePath": "${workspaceFolder}/impl,${workspaceFolder}/test",`

**Comment by TimZoet** [comment]
Thank you very much for your suggestions! They have been addressed in the latest version.
